name: OpenSSH Secure File Copy
description: |
  Use OpenSSH scp to copy files from workspace to your server
author: utahcon
branding:
  icon: chevrons-right
  color: orange
inputs:
  server:
    description: Remote host
    required: true
  port:
    description: Specifies the port to connect to on the remote host
    required: false
  username:
    description: Username for authentication with server (use Github Secrets only!)
    required: true
  password:
    description: Password for authentication with server (use Github Secrets only!)
    required: false
  private-key:
    description: Private key used for key-based identity (use Github Secrets only!)
    required: false
  source:
    description: "Path you wish to send to remote host. Default: '.'"
    required: true
    default: .
  destination:
    description: Path on remote-host to store files
    required: true
  recursive:
    description: |
      Recursively copy entire directories.  Note that scp follows symbolic links encountered in the tree traversal.
    required: false
    default: false
  jumps:
    description: |
      Connect to the target host by first making an scp connection to the jump host described by destination and then
      establishing a TCP forwarding to the ultimate destination from there.  Multiple jump hops may be specified
      separated by comma characters.
    required: false
  ssh-options:
    description: |
      Can be used to pass options to ssh in the format used in ssh_config.  This is useful for specifying
      options for which there is no separate scp command-line flag.  For full details of the options listed
      below, and their possible values, see ssh_config. Comma separated.

            AddressFamily
            BatchMode
            BindAddress
            BindInterface
            CanonicalDomains
            CanonicalizeFallbackLocal
            CanonicalizeHostname
            CanonicalizeMaxDots
            CanonicalizePermittedCNAMEs
            CASignatureAlgorithms
            CertificateFile
            ChallengeResponseAuthentication
            CheckHostIP
            Ciphers
            Compression
            ConnectionAttempts
            ConnectTimeout
            ControlMaster
            ControlPath
            ControlPersist
            GlobalKnownHostsFile
            GSSAPIAuthentication
            GSSAPIDelegateCredentials
            HashKnownHosts
            Host
            HostbasedAuthentication
            HostbasedKeyTypes
            HostKeyAlgorithms
            HostKeyAlias
            Hostname
            IdentitiesOnly
            IdentityAgent
            IdentityFile
            IPQoS
            KbdInteractiveAuthentication
            KbdInteractiveDevices
            KexAlgorithms
            LogLevel
            MACs
            NoHostAuthenticationForLocalhost
            NumberOfPasswordPrompts
            PasswordAuthentication
            PKCS11Provider
            Port
            PreferredAuthentications
            ProxyCommand
            ProxyJump
            PubkeyAcceptedKeyTypes
            PubkeyAuthentication
            RekeyLimit
            SendEnv
            ServerAliveInterval
            ServerAliveCountMax
            SetEnv
            StrictHostKeyChecking
            TCPKeepAlive
            UpdateHostKeys
            User
            UserKnownHostsFile
            VerifyHostKeyDNS

runs:
  using: docker
  image: docker://utahcon/scp
  args:
    - ${{ inputs.server }}
    - ${{ inputs.port }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.private-key }}
    - ${{ inputs.source }}
    - ${{ inputs.destination }}
    - ${{ inputs.recursive }}
    - ${{ inputs.jumps }}
    - ${{ inputs.ssh-options }}